### ISSUE TITLE
Raccourci pour faire revenir le curser "perfo" au début

### ISSUE THREAD

**Issue by louisbigo** [scrime-u-bordeaux/web-midifile-performer#138]
Actuellement, le seul moyen de rejouer depuis le début est de bouger à la main la boule bleu, ou de faire revenir à 0 le champs "Courant". Serait-il possible d'avoir un bouton raccourci ? En fait j'imagine que ça devrait être le rôle du carré rouge, mais celui-ci semble avoir le même comportement que le bouton pause (actif uniquement lors du jeu). Pourrait-on envisager que le bouton rouge serve plutôt à revenir au début ?

**Comment by NyuBlara** [comment]
I believe this is a duplicate of #120.

**Comment by NyuBlara** [comment]
Close as duplicate of #120
